### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by NevMem** [bulumutka/spfgraph#31]
ans -> and
![изображение](https://user-images.githubusercontent.com/31377120/57353608-b8f7c700-7171-11e9-88ae-f0c451bac611.png)

**Comment by NevMem** [comment]
Vizualizes -> Visualize

Типо иначе это значит, что кнопка она как бы визуализует, но это не так, так как она просто вызывает команду и поэтому на тултипе должно быть написано название действия

![изображение](https://user-images.githubusercontent.com/31377120/57353996-ea24c700-7172-11e9-84bf-a944ca61b4e9.png)

**Comment by NevMem** [comment]
Export as -> Export to

![изображение](https://user-images.githubusercontent.com/31377120/57354111-48ea4080-7173-11e9-805b-ceb9215de1d8.png)

**Comment by NevMem** [comment]
# WOOOOOOOOOOOOOOW !!!!

Heigth -> Height

![изображение](https://user-images.githubusercontent.com/31377120/57354130-5c95a700-7173-11e9-8cef-086cd1c88a98.png)

**Comment by NevMem** [comment]
> 
> 
> ans -> and
> ![изображение](https://user-images.githubusercontent.com/31377120/57353608-b8f7c700-7171-11e9-88ae-f0c451bac611.png)

Зачем html uppercase + правильнее будет javascript
потому что jscript != javascript

Proof:
![изображение](https://user-images.githubusercontent.com/31377120/57354328-d88fef00-7173-11e9-88d1-e1a972a60440.png)

**Comment by bulumutka** [comment]
Good, i see, nice...
